djpaystack/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls',namespace='pages')),
    path('donate/',include('payment.urls',namespace='payment')),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name="landing-page"),
]

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('',views.charge, name='charge'),
    path('verify/<str:reference>', views.verify, name='verify'),

]

pages/models.py
from django.db import models

# Create your models here.

payment/models.py
from django.db import models

# Create your models here.

pages/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'pages/landing.html')

payment/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from pypaystack import Transaction, Customer, Plan
from django.conf import settings

# Create your views here.
def charge(request):
    return render(request, 'payment/checkout.html')

def verify(request, reference):
    transaction = Transaction(settings.SK_KEY)
    response = transaction.verify(reference)
    if response[3]['status'] == 'success':
        return render(request,'pages/success.html')
    else:
        return HttpResponse('failed')
    # return HttpResponse(response)

pages/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}Document{%endblock%}</title>
    {% block styles %}{%endblock%}
</head>
<body style="font-family:  Century Gothic;">
    {% block content %}{% endblock %}
</body>
</html>

pages/templates/pages/landing.html
{% extends 'layout.html '%}
{% load static %}
{% block title %} HOME {%endblock%}
{% block styles %}
    <style>
        *{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        header{
            background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)),url(https://esda.imfast.io/img/header.jpg);
            height: 100vh;
            background-position: center;
            background-size: cover;
        }
        ul{
            float: right;
            list-style-type: none;
            margin-top: 25px;
        }
        ul li{
            display: inline-block;
        }
        ul li a {
            text-decoration: none;
            color: #fff;
            padding: 5px 20px;
            border: 1px solid transparent;
            transition: 0.8s ease;
        }
        .active a {
            background-color: #fff;
            color: #000;
        }
        ul li a:hover {
            background-color: #fff;
            color: #000;
        }
        #logo img{
            float: left;
            width: 150px;
            height: auto;
        }
        #main{
            max-width: 1200px;
            margin: auto;
        }
        #title {
            text-align: center;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%,-50%);
        }
        #title h1{
            color: #fff;
            font-size: 70px;
        }
        #button{
            position: absolute;
            top: 70%;
            left: 50%;
            transform: translate(-50%,-50%);
        }
        .btn{
            border: 1px solid #fff;
            padding: 10px 30px;
            color: #fff;
            text-decoration: none;
            transition: 0.7s ease;
        }
        .btn:hover{
            background-color: #fff;
            color: #000;
        }
        .section{
            /* margin-top: 5%; */
            height: 50vh;
            max-width: 1200px;
            text-align: center;
            margin: auto;
        }
        #intro1{
            background-image: url(https://esda.imfast.io/img/lending-a-helping-hand.webp);
            background-size: cover;
            margin-top: 5%;
            margin-bottom: 5%;
            background-position: center;
            height: 200px;
            border-radius: 10px;
            color: rgba(0,0,0,0.1);

        }
        #intro2{
            background-image: url(https://esda.imfast.io/img/photo-1531206715517-5c0ba140b2b8.jpg);
            background-size: cover;
            margin-top: 5%;
            margin-bottom: 5%;
            background-position: center;
            height: 200px;
            border-radius: 10px;
            color: rgba(0,0,0,0.1);

        }
        .intro{
            display: inline-block;
            width: 45%;
            padding: 20px;
        }
        .intro h2{
            margin-top: 8%;
            margin-bottom: 3%;
        }
        .testimonials{
            height: 100vh;
            width: 100%;
            background-color: #000000;
            color: #ececec;
            text-align: center;
        }
        .fundraise{
            height: 50vh;
            text-align: center;
            margin: auto;
            background-image: url(https://esda.imfast.io/img/send-heart.png);
            background-position: center;
            background-size: contain;
            background-repeat: no-repeat;
            z-index: 1;
            
        }
        #footer{
        
            background-color: #231903;
            color: #9dc6a7;
            height: 10vh;
        }
        .footer{
            padding: 30px 20px;
            max-width: 1200px;
            text-align: center;
            margin: auto;
        }
        .footer span{
            border-right: 1px solid ;
            padding: 10px 30px;
        }
        .dbtn{
            background: #fcbf1e;
            color: #120136;
            border: 1px solid #120136
            border-radius: 20px;
            font-weight: bolder;
            position: fixed;
            bottom: 20px;
            left: 20px;

        }
        #logo span{
            float: left;
            margin-top: 2%;
            color: #FFF;
            font-size: 1.5rem; 
            font-weight: bolder;
        }
        #myVideo {
            height: 100%;
            position: static;
            right: 0;
            bottom: 0;
            min-width: 100%;
            min-height: 100%;
}

        /* Add some content at the bottom of the video/page */
        .content {
            position: relative;
            bottom: 150px;
            background: rgba(0, 0, 0, 0.5);
            color: #f1f1f1;
            width: 100%;
            padding: 20px;
        }

/* Style the button used to pause/play the video */
#myBtn {
  width: 200px;
  font-size: 18px;
  padding: 10px;
  border: none;
  background: #000;
  color: #fff;
  cursor: pointer;
}

#myBtn:hover {
  background: #ddd;
  color: black;
}

        
       
       


    </style>
{% endblock %}
    
{% block content %}
<header>
    <div id="main">
        <div id="logo"><img src="https://esda.imfast.io/img/logo.png" alt=""><span>ESDA</span></div>
        <ul>
            <li><a href="{% url 'pages:landing-page' %}">Home</a></li>
            <li><a href="#test" >What We DO</a></li>
            <li><a href="">About</a></li>
        </ul>
    </div>
    <div id="title"><h1>Heal The World</h1></div>
    <div id="button">
        <a class="btn" href="{% url 'payment:charge' %}">change a live today</a>
    </div>
    <a class="btn dbtn" href="{% url 'payment:charge' %}">donate</a>
</header>
<section id="section" class="section">
    <div id="intro" class="intro">
        <h2>The Motivation</h2>
        <p>Growing a flower mandatorily requires soil, water sunlight, labor and patience.
        Thats how to keep a balance in our unbalanced world.
        Everything corelates, we need each other for our survival.
        </p>
        <p>
            Here comes a situation where lives are way too farther apart. 
            A huge part of our societies are very disadvantaged and lacking. 
            We got the <strong>disabled</strong>, <strong>the poor</strong>, <strong>the homeless</strong>,
            <strong>the orphans</strong> and <strong>calamity infested areas</strong>.
        </p>
    </div>
    
</section>
<section id="section" class="section">
    <div id="intro1" class="intro">
        <h2>Moving People From Poverty to Possibilities</h2>
        <p>Your gift to  our charity campaign changes lives of hundrends to thousands.
            Through you and our various programs, the disadvantaged part of our societies
            are given hope to live.
        </p>
    </div>
    <div class="intro">
        <h2>Moving People From Poverty to Possibilities</h2>
        <p>Your gift to  our charity campaign changes lives of hundrends to thousands.
            Through you and our various programs, the disadvantaged part of our societies
            are given hope to live.
        </p>
    </div>
</section>
<section id="section" class="section">
    <div class="intro">
        <h2>Get Your Collegues Together</h2>
        <p>You and your environment can together impact lives in rural africa, 
            providing some shelter, food and good water supply amongst others. 
        </p>
    </div>
    <div id="intro2" class="intro">
        <h2>Get Your Collegues Together</h2>
        <p>You and your environment can together impact lives in rural africa, 
            providing some shelter, food and good water supply amongst others. 
        </p>
    </div>
</section>
<section id="test" class="testimonials">
    <video autoplay muted loop id="myVideo">
        <source src="https://esda.imfast.io/img/rain.mp4" type="video/mp4">
      </video>
      
      <!-- Optional: some overlay text to describe the video -->
      <div class="content">
        <h1>Prepare for the better</h1>
        <p>When the Unexpected happens people struggle. Make room and plans for contingencies</p>
        <!-- Use a button to pause/play the video with JavaScript -->
        <button id="myBtn" onclick="myFunction()">Pause</button>
      </div>
    
</section>
<section style="background-color: #f4eeffef;" class=" fundraise" >

</section>
<section id="footer">
    <div class="footer">
        <span>gyimah.charity@yahoo.com</span> <span><strong>ESDA</strong>.org</span> <span>You can make a difference</span>
    </div>
</section>

<script>
    // Get the video
var video = document.getElementById("myVideo");

// Get the button
var btn = document.getElementById("myBtn");

// Pause and play the video, and change the button text
function myFunction() {
  if (video.paused) {
    video.play();
    btn.innerHTML = "Pause";
  } else {
    video.pause();
    btn.innerHTML = "Play";
  }
}
</script>
{% endblock%}

pages/templates/pages/success.html
{% extends 'layout.html'%}
{% load static %}
{% block styles %}
   <style>
      *{
         margin: 0;
         padding: 0;
         box-sizing: border-box;
      }
      .hbtn{
         text-decoration: none;
         padding: 40px;
         position: absolute;
         top: 5%;
         left: 5%;
         transform: translate(-5%);
         border: 1px solid #fff;
         transition: 0.7s ease;
         color: #fff;
      }
      a:hover{
         color: #000;
         background: #fff;
      }
   </style>
{% endblock %}
{% block content %}
   <header style="height: 100vh; 
        background: url(https://esda.imfast.io/img/thankyou.jpg);
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center;">
      <a class="hbtn" href="{% url 'pages:landing-page' %}">HOME</a>

   </header> 
{% endblock %}

payment/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
        {% block styles%}
    
        {% endblock %}
</head>
<body>
    {% block content%}
    {% endblock %}
</body>
</html>

payment/templates/payment/checkout.html
{% load static %}
{%block styles%}
  <style>
    body{
      background-image: url(https://esda.imfast.io/img/donate.jpg);
      background-size: auto;
      background-position: center;
      margin: 0;
      box-sizing: border-box;
      }
      form{
        
        display: inline-block;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%,-50%);
        overflow: hidden;
        width: 50%;
        padding: 20px;
        text-align: center;
    }
    #form-content{
      background-color: #22283156;
      border-radius: 20px;
      width: 80%;
      margin: auto;
      padding-top: 10px;
    }
    #form-content label{
      display: block;
      font-size: 20px;
    }
    .inp-div{
      width: 80%;
      margin: auto;
      padding: 10px;
    }
    input[type="text"]{
      color: #d8ebb5a6;
      text-align: left;
      padding: 10px;
      width: 60%;
      outline: none;
      border: none;
      background: none;
      font-size: 16px;
      border-left: 1px solid #d8ebb5a6;
      border-right: 1px solid #d8ebb5a6;
      border-bottom: 1px solid #d8ebb5a6;


    }
    input[type="text"]::placeholder{
      color: #d8ebb5a6;
      text-align: left;
    }
    input[type="text"]:active{
      background: transparent;
    }
    .btn{
      font-size: 18px;
      cursor: pointer;
      background: #06623b;
      width: 50%;
      margin: auto;
      text-align: center;
      padding: 10px 20px;
      border: 1px solid rgba(53, 93, 68, 0.431);
      border-radius: 10px;
      color: cornsilk;
      
    }
    .hbtn{
         text-decoration: none;
         padding: 40px;
         position: absolute;
         top: 10%;
         left: 50%;
         transform: translate(-50%);
         border: 1px solid #fff;
         transition: 0.7s ease;
         color: #fff;
      }
      a:hover{
         color: #000;
         background: #fff;
      }
  </style>
{% endblock %}
{% block content%}
<a class="hbtn" href="{% url 'pages:landing-page' %}">HOME</a>

<form >
  <div id="form-content">
    <div class="inp-div">
        <input type="text" id="amount" placeholder="amount eg. 100" required>
    </div>
    <div class="inp-div">
        <input type="text" id="email" placeholder="email address" required>
    </div>
    <div class="inp-div">
        <input type="text" id="full-name" placeholder="Full Name">
    </div>
    <div class="inp-div">
        <input type="text" id="mobile-number" placeholder="Phone Number">
    </div>
    <script src="https://js.paystack.co/v1/inline.js"></script>
    <div class="inp-div">
      <button class="btn" type="button" onclick="payWithPaystack()"> Donate </button> 
    </div>
  </div>
</form>
 
<script>
  function payWithPaystack(){
    var amount = document.getElementById("amount").value;
    var email = document.getElementById("email").value;
    var fullname = document.getElementById("full-name").value;
    var mobile_number = document.getElementById("mobile-number").value;

    var handler = PaystackPop.setup({
      key: 'pk_live_a18ef657a1115197d4a8639aa77462cb7f24f211',
      email: email,
      amount: amount * 100,
      currency: "GHS",
      ref: ''+Math.floor((Math.random() * 1000000000) + 1), // generates a pseudo-unique reference. Please replace with a reference you generated. Or remove the line entirely so our API will generate one for you
      metadata: {
         custom_fields: [
           {
            display_name: "Name",
            variable_name: "fullname",
            value: fullname
           },
            {
                display_name: "Mobile Number",
                variable_name: "mobile_number",
                value: mobile_number
            }
         ]
      },
      callback: function(response){
        ref = response.reference
        window.location =" {% url 'payment:verify' 1234 %}".replace(/1234/,ref) ;
          // alert('success. transaction ref is ' + response.reference);
      },
      onClose: function(){
          alert('window closed');
      }
    });
    handler.openIframe();
  }
</script>
 {% endblock %}
  